# Generated by Django 5.1.4 on 2025-01-11 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='blog.country')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('object_id', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='blog.city')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('visit_date', models.DateTimeField()),
                ('taste_rating', models.IntegerField(choices=[(1, 'Bardzo słabo'), (2, 'Słabo'), (3, 'Średnio'), (4, 'Dobrze'), (5, 'Bardzo dobrze'), (6, 'Celująco')])),
                ('price_rating', models.IntegerField(choices=[(1, 'Bardzo słabo'), (2, 'Słabo'), (3, 'Średnio'), (4, 'Dobrze'), (5, 'Bardzo dobrze'), (6, 'Celująco')])),
                ('restaurant_rating', models.IntegerField(choices=[(1, 'Bardzo słabo'), (2, 'Słabo'), (3, 'Średnio'), (4, 'Dobrze'), (5, 'Bardzo dobrze'), (6, 'Celująco')])),
                ('overall_rating', models.IntegerField(choices=[(1, 'Bardzo słabo'), (2, 'Słabo'), (3, 'Średnio'), (4, 'Dobrze'), (5, 'Bardzo dobrze'), (6, 'Celująco')])),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.restaurant')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
